permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

encoding: utf-8

author:
name: Perry Wang
email: 339359521@163.com

# disqus  config
disqus:
  shortname: wpbleach